"""Added trade system tables

Revision ID: 0e02e43b2da7
Revises: 158fbe2c34d4
Create Date: 2026-05-07 10:43:02.125361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e02e43b2da7'
down_revision: Union[str, Sequence[str], None] = '158fbe2c34d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', 'BUY', 'SELL', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_pnl_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uk_user_balance')
    )
    op.create_index(op.f('ix_user_balances_user_id'), 'user_balances', ['user_id'], unique=False)
    op.create_table('user_holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uk_user_stock')
    )
    op.create_index(op.f('ix_user_holdings_stock_id'), 'user_holdings', ['stock_id'], unique=False)
    op.create_index(op.f('ix_user_holdings_user_id'), 'user_holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_holdings_user_id'), table_name='user_holdings')
    op.drop_index(op.f('ix_user_holdings_stock_id'), table_name='user_holdings')
    op.drop_table('user_holdings')
    op.drop_index(op.f('ix_user_balances_user_id'), table_name='user_balances')
    op.drop_table('user_balances')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
