"""Update user schema

Revision ID: 42d467491c3b
Revises: 0e02e43b2da7
Create Date: 2026-05-07 10:59:35.131592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d467491c3b'
down_revision: Union[str, Sequence[str], None] = '0e02e43b2da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'initial_balance')
    # ### end Alembic commands ###
