"""update schema

Revision ID: 98f399468fc1
Revises: d3ed9085bf9e
Create Date: 2026-05-20 10:02:35.249353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98f399468fc1'
down_revision: Union[str, Sequence[str], None] = 'd3ed9085bf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('symbol', sa.String(), nullable=False))
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('stocks', 'last_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('stocks', 'prev_close',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('stocks', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('stocks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_market'), table_name='stocks')
    op.create_unique_constraint(None, 'stocks', ['symbol'])
    op.drop_column('stocks', 'description')
    op.drop_column('stocks', 'code')
    op.drop_column('stocks', 'listing_date')
    op.drop_column('stocks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('stocks', sa.Column('listing_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('stocks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_market'), 'stocks', ['market'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.alter_column('stocks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stocks', 'change_rate',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('stocks', 'prev_close',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stocks', 'last_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('stocks', 'symbol')
    # ### end Alembic commands ###
